spring:
  datasource:
    url: jdbc:postgresql://medibox-db.postgres.database.azure.com:5432/pillbox_database
    username: mauadmin
    password: Pelotita123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
