spring:
  datasource:
    url: jdbc:postgresql://azure-mau-postgre.postgres.database.azure.com:5432/pillbox_database
    username: mau
    password: Li@nel2022
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
